# Copyright (C) 2019  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'

services:
  collectd:
    build:
      context: ./collectd
      dockerfile: Dockerfile.amd64
    container_name: collectd
    restart: always
    privileged: true
    network_mode: host
    volumes:
    - /dev/sda1:/dev/sda1:ro
    - /dev/sdb2:/dev/sdb2:ro
    - /proc:/mnt/proc:ro
    - /home.new/brick/recordings.local:/rec.local:ro
    - /home.new/brick/recordings.sda1:/rec.sda1:ro
    - ./collectd/collectd.conf:/etc/collectd/collectd.conf
