{
 "title": "Snowfox",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Location",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "now",
     "type": "grafana-clock-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Position",
     "type": "pr0ps-trackmap-panel",
     "gridPos": { "h": 11, "w": 10, "x": 4, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "position",
       "select": [
        [
         { "params": [ "latitude" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "longitude" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "uptime (GoldenPC)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uptime_value",
       "query": "SELECT \"value\" FROM \"uptime_value\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "goldenpc" }
       ]
      }
     ]
    },
    {
     "title": "uptime (Brick)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "uptime_value",
       "query": "SELECT \"value\" FROM \"uptime_value\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "brick" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MasterVolt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "State of Charge",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "statsd_value",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "MasterVolt.StateOfCharge" }
       ]
      }
     ]
    },
    {
     "title": "current",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
     "format": "amp",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "statsd_value",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "MasterVolt.A" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "GoldenPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU temp",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "temp1" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "goldenpc" }
     ]
    }
   ]
  },
  {
   "title": "sdb2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "data" }
     ]
    }
   ]
  },
  {
   "title": "system load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\") FROM \"cpu_value\" WHERE (\"type_instance\" = 'idle' AND \"host\" = 'goldenpc') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "can0",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "can0" }
     ]
    }
   ]
  },
  {
   "title": "can0",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "can0" }
     ]
    }
   ]
  },
  {
   "title": "can2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "can2" }
     ]
    }
   ]
  },
  {
   "title": "can3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "can3" }
     ]
    }
   ]
  },
  { "title": "Brick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU temp",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "temp1" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "brick" }
     ]
    }
   ]
  },
  {
   "title": "sdb2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "rec.local" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "brick" }
     ]
    }
   ]
  },
  {
   "title": "sda1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "rec.sda1" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "brick" }
     ]
    }
   ]
  },
  {
   "title": "system load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\") FROM \"cpu_value\" WHERE (\"type_instance\" = 'idle' AND \"host\" = 'brick') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "GPU temp",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cuda_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "temperature_gpu" }
     ]
    }
   ]
  },
  {
   "title": "Trimble",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 17 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_value",
     "query": "SELECT last(\"value\") FROM \"ping_value\" WHERE (\"host\" = 'brick' AND \"type_instance\" = '10.42.42.41' AND \"type\" = 'ping') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "10.42.42.40" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ping" }
     ]
    }
   ]
  },
  {
   "title": "Applanix",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 17 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "10.42.42.40" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ping" }
     ]
    }
   ]
  },
  {
   "title": "HDL32e",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 17 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "10.42.42.70" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ping" }
     ]
    }
   ]
  },
  {
   "title": "Axis",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "10.42.45.50" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ping" }
     ]
    }
   ]
  },
  {
   "title": "Basler left",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "10.42.43.50" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ping" }
     ]
    }
   ]
  },
  {
   "title": "BoB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp0s25" }
     ]
    }
   ]
  },
  { "title": "Network (Brick)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "enp4s0 (Axis)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Axis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp4s0" }
     ]
    }
   ]
  },
  {
   "title": "enp5s0 (Basler left)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Basler left",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp5s0" }
     ]
    }
   ]
  },
  {
   "title": "enp0s25 (BoB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BoB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "brick" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "enp0s25" }
     ]
    }
   ]
  }
 ]
}